### ISSUE TITLE
Update for flutter web

### ISSUE THREAD

**Issue by alfaruqrizqi18** [KINTO-JP/ogp_data_extract#3]
Running on flutter web it seems have CORS issue, because it receive `null`
Any advice? @KINTO-JP need to get image from url

**Comment by KINTO-JP** [comment]
@alfaruqrizqi18 
Thank you for telling me. 
If that problem is happening in the development environment, try one of these things:

- Method 1
Run the following command:
`flutter run -d chrome --web-browser-flag "--disable-web-security"`

or

- Method 2

1. **Delete a file**:
   - Go to the folder `flutter\bin\cache`.
   - Find and delete the file named `flutter_tools.stamp`.

2. **Change a file**:
   - Go to the folder `flutter\packages\flutter_tools\lib\src\web`.
   - Open the file named `chrome.dart` in a text editor (like VSCode).

3. **Edit the file**:
   - Look for the line that says `disable-extensions`.
   - Right below this line, add a new line that says `disable-web-security`.
